version: '3.8'

services:
  apache:
    build: ./apache-php
    container_name: apache_phalcon
    ports:
      - "8085:80"
    volumes:
      - ./app:/var/www/html
      - ./app/cache/volt:/var/www/cache/volt
    depends_on:
      - mysql

  mysql:
    image: mysql:8.2
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: cr00n
      MYSQL_DATABASE: docker-lamp
      MYSQL_USER: admin
      MYSQL_PASSWORD: cr00n
    # ports:
    #   - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "8086:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306

volumes:
  mysql_data:
